[package]
name = "flatpath-cli"
version = "0.0.0"
authors = ["John Teske <john.teske@protonmail.com>"]
edition = "2018"

[dependencies]
projects = { path = "../projects" }
clap = { version = "2.33.3", default-features = false }
