[package]
name = "flatpath"
version = "0.1.0"
authors = ["John Teske <john.teske@protonmail.com>"]
edition = "2018"

[dependencies]
flatpath-core = { path = "../flatpath-core" }
flatpath-derive = { path = "../flatpath-derive" }
svg = "0.9.2"
